language: python
sudo: false
python:
    - 'nightly'
    - '3.6'
    - '3.5'
    - '3.4'
    - '3.3'
    - '2.7'
    - '2.6'
    - 'pypy'
    - 'pypy3'
install:
    - pip wheel -f wheelhouse coverage biopython cython pysam pyvcf numpy || true
    - pip install -f wheelhouse biopython cython pysam pyfasta coverage pyvcf numpy || true
    - python setup.py install
    - if [ ! -f samtools-1.2 ]; then curl -sL https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 | tar -xjv; fi
    - cd samtools-1.2
    - make
    - export PATH=$PATH:$PWD
    - cd ..
    - if [ ! -f htslib-1.4 ]; then curl -sL https://github.com/samtools/htslib/releases/download/1.4/htslib-1.4.tar.bz2 | tar -xjv; fi
    - cd htslib-1.4
    - make
    - export PATH=$PATH:$PWD
    - cd ..
before_script:
    - if [ $(python --version) -gt 2.6 ]; then env pip install biopython; fi
    - env python tests/data/download_gene_fasta.py
script: nosetests --with-coverage --cover-package=pyfaidx
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: MbSaeuitkVTZqxa0PJ3RcR1aMf+B/sMbcx2sWOo9xfLlRFDFpYWJZ0EfXWEhrVu2YWXpBsasgunTDWSi0jNcZMH92MzOC+UTVYr45LO5sy6hm4iSiAgm/DPgYWdjP0SFKr7eL/HWPS+gHvgkXL1upleX21O358bxaezoasuKFvs=
  on:
    all_branches: true
    python: 2.7
    tags: true
    repo: mdshw5/pyfaidx
matrix:
  allow_failures:
    - python: 'nightly'
    - python: 'pypy3'
    - python: 'pypy'
  fast_finish: true
cache:
    directories:
        - tests/data
        - samtools-1.2
        - htslib-1.4
        - wheelhouse
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - if [ $TRAVIS_PYTHON_VERSION == '3.4' ] && [ $TRAVIS_TAG ]; then python scripts/benchmark.py 1000; fi
